#!/bin/bash
VERSION="1.2"

function showVersion {
    echo "watch-util v${VERSION}"
}

function showHelp {
    showVersion
    cat << EOF
./watch-util [option] [command...]
Utility functions for AsteroidOS device.  By default, uses "SSH Mode"
but can also use "ADB Mode."

Available options:
-h or --help    prints this help screen and quits
-a or --adb     uses ADB command to communicate with watch
-p or --port    specifies a port to use for ssh and scp commands
-r or --remote  specifies the remote (watch)  name or address for ssh and scp commands
-q or --qemu    communicates with QEMU emulated watch (same as -r localhost -p 2222 )
-v or --version displays the version of this program

Available commands:
backup BD       backs up settings of currently connected watch to directory BD
restore BD      restores previously saved settings from dir BD to connected watch
fastboot        reboots into bootloader mode
forgetkeys      forgets the ssh keys for both "watch" and "192.168.2.15"
present         return true if watch is present, otherwise false
snap            takes a screenshot and downloads it to a local jpg file
settime         sets the time on the watch according to the current time on host
listtimezones   lists the timezones known to the watch
settimezone TZ  sets the timezone on the watch to the passed timezone
wallpaper WP    sets the wallpaper on the watch to named file WP
restart         restarts the ceres user on the watch
reboot          reboots the watch
wait MSG        wait for a watch to connect while displaying MSG
routing         sets up the routing to go through the local host and DNS 1.1.1.1
pushface WF     pushes the named watchface to the watch (point to WF directory)
watchface WF    sets the active watchface to the named watchface
screen on|off   sets the screen always on or normal mode

EOF
}

function doWatchCommand {
    local user="$1"
    local cmd=$2
    case ${user} in 
        root)
            if [ "${ADB}" == true ] ; then
                adb shell "${cmd}"
            else
                ssh -p "${WATCHPORT}" -t root@"${WATCHADDR}" ${cmd}
            fi
            ;;
        ceres)
            if [ "${ADB}" == true ] ; then
                printf -v cmd %q "${cmd}"
                adb shell "su -l -c ${cmd} ceres"
            else
                ssh -p "${WATCHPORT}" -t ceres@"${WATCHADDR}" ${cmd}
            fi
            ;;
        *)
            echo "Error: unknown watch user ${user}"
            ;;
    esac
}

function setDconf {
    local dconfsetting="$1"
    local filename="$2"
    doWatchCommand "ceres" "dconf write ${dconfsetting} '\"file://${filename}\"'"
}

function pushFiles {
    local user="$1"
    local sourcedir="$2"
    local destdir="$3"
    if [ "${ADB}" = true ] ; then
        if [ "${user}" != "root" ] && [[ "${destdir::1}" != '/' ]] ; then
            destdir="/home/${user}/${destdir}"
        fi
        adb push ${sourcedir} "${destdir}"
    else
        scp -P"${WATCHPORT}" -r ${sourcedir} "${user}@${WATCHADDR}:${destdir}"
    fi
}

function pullFiles {
    local user="$1"
    local sourcedir="$2"
    local destdir="$3"
    if [ "${ADB}" = true ] ; then
        if [ "${user}" != "root" ] && [[ "${sourcedir::1}" != '/' ]] ; then
            sourcedir="/home/${user}/${sourcedir}"
        fi
        adb pull ${sourcedir} "${destdir}"
    else
        scp -P"${WATCHPORT}" -r "${user}@${WATCHADDR}:${sourcedir}" "${destdir}"
    fi
}

function pushWatchface {
    pushFiles "root" "${1}"'/usr/share/*' "/usr/share/"
}

function pushWallpaper {
    local source="$1"
    local wallpaper
    local destination="/usr/share/asteroid-launcher/wallpapers/full/${wallpaper}"
    wallpaper="$(basename "$1")"
    pushFiles "root" "${source}" "${destination}"
    setDconf "/desktop/asteroid/background-filename" "${destination}"
}

function restartCeres {
    doWatchCommand "root" "systemctl restart user@1000"
}

function activateWatchface {
    setDconf "/desktop/asteroid/watchface" "/usr/share/asteroid-launcher/watchfaces/${1}.qml"
}

function setTimeZone {
    doWatchCommand "root" "timedatectl set-timezone $1"
}

function forgetKeys {
    ssh-keygen -R ${WATCHADDR}:${WATCHPORT}
    ssh-keygen -R ${WATCHADDR}
    ssh-keygen -R watch
}

function watchPresent {
    local result=false
    if [ "${ADB}" == true ] ; then
        if [ "$(adb get-state 2>/dev/null)" = "device" ] ; then
            result=true
        fi
    else
        if route |grep 192.168.2.0 > /dev/null ; then
            result=true
        fi
    fi
    echo "${result}"
}

function waitWatch {
    echo "$1"
    if [ "${ADB}" == true ] ; then
        adb wait-for-usb-device
    else
        while ! route |grep 192.168.2.0 > /dev/null ; do 
            sleep 1
        done
    fi
}

function setTime {
    doWatchCommand "root" "date -s @`(date -u +"%s" )`"
}

function getScreenshot {
    doWatchCommand "ceres" "screenshottool /home/ceres/screenshot.jpg 0"
    pullFiles "ceres" "/home/ceres/screenshot.jpg" "$(date +%Y%m%d_%H%M%S).jpg"
}

function setRouting {
# get this host's IPv4 address
    MYADDR=$(doWatchCommand "root" "who" | awk '{gsub(/[()]/, "", $NF); print $NF}')
    doWatchCommand "root" "ip route add default via ${MYADDR}"
    doWatchCommand "root" 'echo "nameserver 1.1.1.1" >> /etc/resolv.conf'
}

function backupSettings {
    local backupdir="$1"
    pullFiles "ceres" "/home/ceres/.config" "${backupdir}/ceresconfig"
    pullFiles "root" "/var/lib/connman" "${backupdir}/connman"
}

function restoreSettings {
    local backupdir="$1"
    pushd "${backupdir}/ceresconfig" || exit
    pushFiles "ceres" "*" "/home/ceres/.config/"
    cd "${backupdir}/connman" || exit
    pushFiles "root" "*" "/var/lib/connman"
    popd || exit
}

function screen {
    if [ "$1" = "on" ] ; then
        doWatchCommand "root" "mcetool -D on"
    else
        doWatchCommand "root" "mcetool -D off"
    fi
}

# These are the defaults for SSH access
WATCHPORT=22
WATCHADDR=192.168.2.15
# These are the defaults for local QEMU target
QEMUPORT=2222
QEMUADDR=localhost
# Assume no ADB unless told otherwise
ADB=false

while [[ $# -gt 0 ]] ; do
    case $1 in 
        -a|--adb)
            ADB=true
            shift
            ;;
        -q|--qemu)
            WATCHPORT=${QEMUPORT}
            WATCHADDR=${QEMUADDR}
            shift
            ;;
        -p|--port)
            WATCHPORT="$2"
            shift
            shift
            ;;
        -r|--remote)
            WATCHADDR="$2"
            shift
            shift
            ;;
        -h|--help)
            showHelp
            exit 1
            ;;
        -v|--version)
            showVersion
            shift
            ;;
        backup)
            backupSettings "$2"
            shift
            shift
            ;;
        restore)
            restoreSettings "$2"
            shift
            shift
            ;;
        present)
            watchPresent
            shift
            ;;
        fastboot)
            doWatchCommand "root" "reboot bootloader"
            shift
            ;;
        screen)
            screen "$2"
            shift
            shift
            ;;
        snap)
            getScreenshot
            shift
            ;;
        settime)
            setTime
            shift
            ;;
        settimezone)
            setTimeZone "$2"
            shift
            shift
            ;;
        pushface)
            pushWatchface "$2"
            shift
            shift
            ;;
        forgetkeys)
            forgetKeys
            shift
            ;;
        listtimezones)
            doWatchCommand "root" "timedatectl list-timezones"
            shift
            ;;
        wallpaper)
            pushWallpaper "$2"
            shift
            shift
            ;;
        reboot)
            doWatchCommand "root" "reboot"
            shift
            ;;
        restart)
            restartCeres
            shift
            ;;
        wait)
            waitWatch "$2"
            shift
            shift
            ;;
        routing)
            setRouting
            shift
            ;;
        watchface)
            activateWatchface "$2"
            shift
            shift
            ;;
        *)
            echo "Ignoring unknown option $1"
            shift
            ;;
    esac
done 

